version: '3.8'

services:
  ai-server:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./service_account.json:/app/service_account.json:ro
    restart: unless-stopped
