name: PR Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies Test
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Docker Build Test
      run: |
        echo "Testing Docker build..."
        docker build -t test-image .
        echo "Docker build successful!"

  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install QA Tools
      run: pip install black isort flake8

    - name: Code Quality Checks
      continue-on-error: true
      run: |
        echo "Code formatting..."
        black --check . || echo "Warning: Formatting issues found"
        echo "Import sorting..."
        isort --check-only . || echo "Warning: Import sorting issues found"
        echo "Linting..."
        flake8 . --count --statistics --max-line-length=100 || echo "Warning: Linting issues found"

  summary:
    runs-on: ubuntu-latest
    needs: [validate, code-quality]
    if: always()
    steps:
    - name: PR Summary
      run: |
        echo "## PR Validation Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**PR:** #${{ github.event.number }}" >> $GITHUB_STEP_SUMMARY
        echo "**Branch:** ${{ github.head_ref }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Results:" >> $GITHUB_STEP_SUMMARY
        echo "- Core Validation: ${{ needs.validate.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- Code Quality: ${{ needs.code-quality.result }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ "${{ needs.validate.result }}" == "success" ]]; then
          echo "### Ready to Merge!" >> $GITHUB_STEP_SUMMARY
          echo "All core validations passed successfully." >> $GITHUB_STEP_SUMMARY
        else
          echo "### Issues Found" >> $GITHUB_STEP_SUMMARY  
          echo "Please fix validation errors before merging." >> $GITHUB_STEP_SUMMARY
        fi
