name: Test Deployment

on:
  workflow_dispatch:  # Manual trigger only

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Test Secrets
      run: |
        echo "Testing secrets availability..."
        if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
          echo "❌ PAT_TOKEN is missing"
          exit 1
        else
          echo "✅ PAT_TOKEN is available"
        fi
        
        if [ -z "${{ secrets.VM_IP }}" ]; then
          echo "❌ VM_IP is missing"
          exit 1
        else
          echo "✅ VM_IP is available: ${{ secrets.VM_IP }}"
        fi
        
        if [ -z "${{ secrets.VM_SSH_KEY }}" ]; then
          echo "❌ VM_SSH_KEY is missing"
          exit 1
        else
          echo "✅ VM_SSH_KEY is available"
        fi

  test-docker-build:
    runs-on: ubuntu-latest
    needs: test-secrets
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Check requirements.txt
      run: |
        if [ ! -f "requirements.txt" ]; then
          echo "❌ requirements.txt not found"
          exit 1
        else
          echo "✅ requirements.txt found"
          echo "Content:"
          cat requirements.txt
        fi

    - name: Test Docker Build
      run: |
        echo "Testing Docker build..."
        docker build -t test-image .
        echo "✅ Docker build successful"

  test-registry-login:
    runs-on: ubuntu-latest
    needs: test-secrets
    steps:
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_TOKEN }}
    
    - name: Test Registry Access
      run: |
        echo "✅ Registry login successful"
        echo "Registry: ${{ env.REGISTRY }}"
        echo "Image name: ${{ env.IMAGE_NAME }}"
